### ISSUE TITLE
Issue with the bot 

### ISSUE THREAD

**Issue by iSweaZzy** [denverquane/amonguscapture#103]
Hello, I have an issue with the bot when I start it, the capture works but I block here 

<img width="679" alt="Capture d’écran 2020-11-26 à 23 06 43" src="https://user-images.githubusercontent.com/22794905/100394065-14332800-303c-11eb-990c-13f482f65112.png">

**Comment by Cretezy** [comment]
Restart the game and capture. Seems like the latest version has some overflow bug.

**Comment by Cretezy** [comment]
![image](https://user-images.githubusercontent.com/2672503/100416955-ba3b5e00-304d-11eb-85f8-97ea6425ab58.png)

**Comment by CarbonNeuron** [comment]
Make sure your game is up to date. Also please enable debug mode, restart capture and post logs of the console output.

**Comment by iSweaZzy** [comment]
Thank you it is good ! It is repaired
