### ISSUE TITLE
2020.12.3

### ISSUE THREAD

**Issue by vrnagy** [denverquane/amonguscapture#108]
I saw You have updated the Offsets.json, but my client can't detect the room code with version 2020.12.3

As You can see on the attached screenshot the offsets are loaded, but the lobby is not recognized.

Thanks

![image](https://user-images.githubusercontent.com/199546/101212885-c2148700-3679-11eb-9083-8349cea996bc.png)

**Comment by CarbonNeuron** [comment]
We updated offsets again just after you made this post. Please relaunch capture and try again.

**Comment by smiller171** [comment]
Working now for me! I think this can close
