### ISSUE TITLE
[Feature] Add auto connect to host at launch

### ISSUE THREAD

**Issue by Dragoon1010** [denverquane/amonguscapture#115]
It's possible to add a checkbox, for auto connection at launch, with parameters setted in "manual connection" section ? :)

**Comment by CarbonNeuron** [comment]
I will implement this later today.

**Comment by CarbonNeuron** [comment]
How would we handle the connect code? Because I think that would change

**Comment by CarbonNeuron** [comment]
This is not really a feature that I think is super useful. Sorry but I think I will be closing this.
