### ISSUE TITLE
Bot Connected to AutoMuteUs but does not mute players.

### ISSUE THREAD

**Issue by Flewrider** [denverquane/amonguscapture#117]
Hey. Using ur bot in connection with the AutoMuteUs bot as suggested and followed your tutorial to connect everything. The Log displays a connection successfull message but the bot does not show "successfully deafened players" messages. 
Will supply log file here.
[CaptureLog.txt](https://github.com/denverquane/amonguscapture/files/5726908/CaptureLog.txt)

One of the devs of automuteus told me it should display such messages.

**Comment by CarbonNeuron** [comment]
Are you talking about the bot that is built into the capture?

**Comment by Flewrider** [comment]
Yes I am. Why is that and how can I fix it?

**Comment by CarbonNeuron** [comment]
Well are you using the official bot or a self hosted one

**Comment by Flewrider** [comment]
The self hosted one. since you are asking like this I guess that doesnt work? I thought it would since they connect via the link i click in the automuteus DM

**Comment by denverquane** [comment]
Wait what? If you're self-hosted, just provide the token directly to the bot, no need to run the bot inside the capture client

**Comment by Flewrider** [comment]
So I have the Automuteus bot self hosted and try to use it connected with the among us capture bot since the API limit stops everyone from getting unmuted at the same time. I thought thats what the among us capture bot was meant to be for: provide additional capacity for the automute us bot

**Comment by Flewrider** [comment]
I dont think you undertood what i wanted but we can discuss in a closed issue

**Comment by Flewrider** [comment]
Ok ignore the link didnt scroll correctly on first click. I now know what you mean. Thank you.
