### ISSUE TITLE
[Bug] Latest release not working correctly on 4K monitor

### ISSUE THREAD

**Issue by AliMirlou** [denverquane/amonguscapture#118]
Release version 2.8.4 does not show the UI when I open it. It seems that it opens outside of the border (bottom right) of my 4K monitor and the problem seems to come from the Scale option in Display settings. The recommended value in my laptop is 250% which actually gives an appropriate UI and any other value makes everything too small or too large.

Commit 38005e766511819fad3e3f18a793a9936850ceec is causing this probably, since the Screen API does not take the scale value into account.

My spec:
Lenovo Y50-70
Windows 10 v20H2 build 19042.685

**Comment by bthulse** [comment]
There is a workaround to this issue. If you lower the display scaling, it should bringthe window into view. Afterwards you can set the scaling back to your perfered setting and it should stay on the screen. However, this must be done each time the application is launched.

**Comment by CarbonNeuron** [comment]
Yeah I noticed this, I know why it does it. It's because windows reports the monitor size but not the scaling, IE: windows still says that the monitor is 4k even tho you only have 4k/display scaling percentage.

**Comment by CarbonNeuron** [comment]
Fixed in cf1fbbd0e9f767f7eddc881e42930cb2ca92c433.
