### ISSUE TITLE
Sign AmongUsCapture.exe to prevent Smartscreen warnings

### ISSUE THREAD

**Issue by HandyHat** [denverquane/amonguscapture#122]
Signing the exe will help prevent Windows Defender Smartscreen warnings and increase trust in the capture program.

![image](https://user-images.githubusercontent.com/58530748/103570738-8f9cba80-4ec1-11eb-9fff-c188c0f7466a.png)

**Comment by CarbonNeuron** [comment]
We would do this, but this is hugely expensive. We would need an Extended validation code signing certificate, and those go for about $300 a year - $700 (from digicert). I don't think this open source software has that kind of money laying around.

**Comment by CarbonNeuron** [comment]
We are open for donations though lol

**Comment by HandyHat** [comment]
Ah I see. No worries - thanks for creating an amazing bot and capture program!
