### ISSUE TITLE
Clearing discord token or settings overall

### ISSUE THREAD

**Issue by tkulpa** [denverquane/amonguscapture#124]
No option to clear discord token, no easy way to reset configuration

If somone is also looking how to clear settings, remove  **%APPDATA%\AmongUsCapture** on windows

**Comment by CarbonNeuron** [comment]
You can technically just put nothing in the box and submit and it should set to nothing I'm pretty sure

**Comment by tkulpa** [comment]
It dosent work with empty input, already tried, you can set it for like 1 character but it will throw error every start up

**Comment by CarbonNeuron** [comment]
Fixed in 33a2969880a45366fbd94846e97e93e239759a7f
