### ISSUE TITLE
AmongUsCapture.exe is detected by Windows Defender as Trojan:Win32/Emali.A!cl

### ISSUE THREAD

**Issue by ianhiddleston** [denverquane/amonguscapture#17]
Threat Detected: Trojan:Win32/Emali.A!cl
Alert Level: Severe
Date 24/09/2020 23:25 (I'd literally just downloaded it to try.)
![Capture](https://user-images.githubusercontent.com/24566428/94206734-0f2bee00-febe-11ea-96a1-52e962cb1a35.PNG)

**Comment by Stenlan** [comment]
That's just windows defender signature scanning. Possibly because the software opens a socket. If you don't trust it, you can build from source. Unfortunately we currently don't really have a way of preventing this issue.
