### ISSUE TITLE
Todo: Auto updater. 

### ISSUE THREAD

**Issue by CarbonNeuron** [denverquane/amonguscapture#21]
With the integration of the CarbonCI projected, all exe files it puts out are versioned. The Capture program can access its own program by reflection.

**Comment by chauffer** [comment]
take a look at https://www.codeproject.com/Articles/5165015/AutoUpdate-A-GitHub-Enabled-autoupdater

**Comment by MetricMike** [comment]
Can we split this issue off into a warn/log message first that we're outdated and then auto-updating later?

**Comment by litetex** [comment]
This may also be helpful: 
https://github.com/Tyrrrz/Onova

**Comment by CarbonNeuron** [comment]
Onova looks great!

**Comment by litetex** [comment]
Note: [Onova](https://github.com/Tyrrrz/Onova) and [AutoUpdate](https://github.com/codewitch-honey-crisis/AutoUpdate) only support Windows

**Comment by CarbonNeuron** [comment]
Well lucky for me I only write the windows branch. @litetex are you in our discord server? We can get you a dev role

**Comment by t00thpick1** [comment]
I'd actually rather see a system where the game offsets are downloaded from the github based on the file hash of the amongus.exe  I could work on this myself and PR it in if yall are interested.  Then the code itself wouldn't need to change with new updates, all that would be needed is a new offsets file uploaded with the new game hash.

**Comment by t00thpick1** [comment]
Actually it may be prudent to have both.  One for code updates as yall planned, and the offset download system so it doesn't require a code update to support new versions.

**Comment by t00thpick1** [comment]
Oh I see this has already been done earlier today..

**Comment by DrewScoggins** [comment]
Did this work ever end up happening? If not I would be happy to take a crack at it.

**Comment by CarbonNeuron** [comment]
Instead we opted to make the offsets update automatically
