### ISSUE TITLE
Will not update state

### ISSUE THREAD

**Issue by devinkid1** [denverquane/amonguscapture#22]
I am running an among us server with 4 people, I run this, but the state wont change at all ingame. All it does is just stay at the "MENU" state.

I am using it with the among us discord bot.

**Comment by CarbonNeuron** [comment]
Are you using release 2.0.7? 2.0.6 was built of the wrong branch

**Comment by devinkid1** [comment]
Oh! i was using 2.0.6 that was probably why. i will try 2.0.7

**Comment by devinkid1** [comment]
nope, the state still stays the same. "MENU"

**Comment by devinkid1** [comment]
![image](https://user-images.githubusercontent.com/42325132/94325866-9c2e8000-ff6e-11ea-843a-dc04d4d7c613.png)

![image](https://user-images.githubusercontent.com/42325132/94325874-a3558e00-ff6e-11ea-9208-61645801d54b.png)

**Comment by CarbonNeuron** [comment]
Are you on the steam version of the game or a cracked copy?

**Comment by devinkid1** [comment]
itch.io

**Comment by devinkid1** [comment]
does it only work with steam?

**Comment by CarbonNeuron** [comment]
It does only work with the steam version

**Comment by devinkid1** [comment]
oh ok, thanks
