### ISSUE TITLE
[Question] Using WinAPI/Native Process Module calls over Process.Modules

### ISSUE THREAD

**Issue by TauAkiou** [denverquane/amonguscapture#32]
Hi. I'm working on a GTK/Linux port of 'amonguscapture', and I have a small question about how the memory reader is obtaining its shared library list.

From what I can tell, .NET Core will list all shared libraries (modules) attached to the program in the Process.Modules member, which when compared to the information I get from /proc/[pid]/maps, appears to be accurate. However, 'amonguscapture' appears to use the Windows native API calls to obtain a list of modules along with information.

I'm asking this because I'm determining the best course of action of pulling shared library locations from the Among Us process in Linux, and I want to know if there's a particular reason to use the OS native Module calls over the built-in list attached to Process.

I'm trying to keep the structure of the Linux memory reader as close as possible to the Windows one that already exists, so I want to know if there's a performance-based or other reason as to why we shouldn't trust 'Process.Modules'.

**Comment by Stenlan** [comment]
Last time I tried it, it didn't show half the modules. Since we're doing low-level calls already anyway, and this way of walking the module list was already implemented, I kept this approach out of laziness. No performance-related reasons. No security measures by Among Us as of yet either, so feel free to do it any other way

**Comment by TauAkiou** [comment]
That's fair. I ended up skipping over Process.Modules anyway because it seems too cumbersome to navigate a ReadOnlyCollection. I ended up taking the OS approach and reading /proc/<pid>/maps to find the module starting point, which works just as well. Thanks for the answer.
