### ISSUE TITLE
New settings implementation throws 'Newtonsoft.Json.JsonException' if Alias contains spaces

### ISSUE THREAD

**Issue by TauAkiou** [denverquane/amonguscapture#39]
While I was testing my modifications for the ProcessMemory rework, I discovered that the configuration engine does not like it when the Alias for a configuration entry contains a space.

I discovered this when attempting to access a field that uses the new GameOffsets configuration value:

```Newtonsoft.Json.JsonException: 'Unexpected character while parsing path:  '```

Changing:

```
[Option(Alias = "Client Offset", DefaultValue = 0x1468840)]
        int AmongUsClientOffset { get; set; }```
```

to:

```
[Option(Alias = "ClientOffset", DefaultValue = 0x1468840)]
        int AmongUsClientOffset { get; set; }
```
eliminates this problem. This has to be done for each Alias that has a space in it.

**Comment by CarbonNeuron** [comment]
Yeah thats just how this works. But anyway, They have been changed to Offset.(name) instead.
