### ISSUE TITLE
Any way to use older Capture with Newer Discord bot? Weird things happen.

### ISSUE THREAD

**Issue by se7enek** [denverquane/amonguscapture#47]
![image](https://user-images.githubusercontent.com/46325161/95597408-de67bf00-0a4e-11eb-9bf4-2e88b08110a9.png)

Basically no way for me to link it.
When i launch Capture.exe, windows "loading" image on cursor, but its all. No program launches. When i run older version, it runs fine.

**Comment by se7enek** [comment]
Screenshot there is the only thing that happens when i use link from DM.

**Comment by CarbonNeuron** [comment]
If you run the capture.exe by itself first then link what happens?

**Comment by se7enek** [comment]
After PC Reboot, i did following steps:
1. Launched Capture.exe (when game was in menu) and window appeared showing some stuff and "Connect Code" but with maximum of 6 chars to type.
2. Then i clicked link from DM message, nothing happened. Same discord message, same in capture.exe, log in discord bot as earlier
3. Then i closed Capture.exe, and when i tried relaunching it, it didnt run. Propably if i would reboot pc again, it would show again but nothing happens so far.

**Comment by se7enek** [comment]
![image](https://user-images.githubusercontent.com/46325161/95604201-9e590a00-0a57-11eb-9f25-3186de0d1ff7.png)

Its not polish but when i try to deinstall .net core, i see multiple apps running in background and deinstaller asks me what to do cuz files are in use.

**Comment by akaplin** [comment]
Confirm @se7enek issue. Can't re-run capture app after closing it. Reboot fix the problem. Same thing with not working DM links.

**Comment by akaplin** [comment]
Ok, now I can re-run capture just killing it's process. But I still can't insert connect code manually cause app cut last symbol of the code.
 
![image](https://user-images.githubusercontent.com/11199210/95609539-82f5fb00-0a67-11eb-9bbd-8baf2c349454.png)

**Comment by se7enek** [comment]
Yep, i tried also using URL from the DM just copy-pasted instead of clicking but doesnt seem to change a thing.

**Comment by se7enek** [comment]
I must say that like 15 reboots later, and removing/reinstalling everything from scratch (couple of times too), and running as Admin app for FIRST TIME, actually helped. Now when i close app, i can relaunch it. Now when app is closed and i click link, it links fine.

**Comment by CarbonNeuron** [comment]
Yeah I know exactly why that is, and a fix was already deployed but we didn't recompile yet. 

Basically I added logging to this release, which is all fine when you launch the program normally. But it is using a relative path. If shell starts the capture, then it technically is in system32 and it doesn't have write access there, so it crashes. Giving it admin gave it the perms to create the log file in System32.

**Comment by CarbonNeuron** [comment]
Should be fixed in latest release.
