### ISSUE TITLE
Issue with .NET Core

### ISSUE THREAD

**Issue by MarcoMusiol** [denverquane/amonguscapture#48]
I've got '.Net Core' installed, but it still shows up, that I need to install it.

I tried to uninstall it and installed the 'dotnet-sdk-3.0.103-win-x86.exe'.

It still didn't worked, so I uninstalled it again and installed the 'dotnet-sdk-2.1.810-win-x86.exe', but it is still not working. I also tried to install and open it as administrator, but nothing is working. 

Can anyone help me maybe?

**Comment by CarbonNeuron** [comment]
To run the apps you don't need the sdk, you need the runtime. And if you're using x86 .net core make sure you are using the x32 release version

**Comment by MarcoMusiol** [comment]
Oh I am sorry, that I forgot to say it, but I also installed the both versions of runtime and it still don't work. :(

**Comment by CarbonNeuron** [comment]
You said you installed 2.1.810? We are on dot net core 3.1.

**Comment by MarcoMusiol** [comment]
I tried to installed 'dotnet-sdk-3.0.103-win-x86.exe', 'dotnet-sdk-2.1.810-win-x86.exe', 'windowsdesktop-runtime-3.1.8-win-x86.exe', 'dotnet-runtime-2.1.22-win-x86.exe' and nothing of it works. :(

**Comment by denverquane** [comment]
Restart your PC?

**Comment by MarcoMusiol** [comment]
I also tried to restart it after every installation 🤔

**Comment by MarcoMusiol** [comment]
![image](https://user-images.githubusercontent.com/64715619/95622535-ff8ed680-0a73-11eb-8221-45ca49f1e902.png)

That is what version I've got installed at the moment and it is still not working. Is it right or is the version wrong?

**Comment by MarcoMusiol** [comment]
Oh, I am sorry guys... Even after you said it I still installed x86 all the time, because I thought this is the 64-bit version. I don't know why I thought it.😅

But thank you all very much for help!
