### ISSUE TITLE
Capture code is cleared when connect button is clicked

### ISSUE THREAD

**Issue by XeonBlue** [denverquane/amonguscapture#51]
When using manual connection rather than URL, I enter the connection code, and when I click Connect, the capture code is cleared instead of sending it to the server.

In the log:
[ClientSocket]: Connection code () sent to server.

Looks like it's in the ConnectButton_Click handler
ConnectCodeBox.Clear();

**Comment by XeonBlue** [comment]
For now I am just commenting that out and building it locally, but something you might want to fix for your next release.

**Comment by CarbonNeuron** [comment]
Oops, pretty sure that's a leftover from when we were only using manual, and it detected that it didn't work. But I guess we commented out the lines above it and not that line lol.

**Comment by Stenlan** [comment]
Fixed in 5a3c1bc3314037828ed95296ad45cb86ac5d950c.
