### ISSUE TITLE
Self contained distributable

### ISSUE THREAD

**Issue by slang25** [denverquane/amonguscapture#54]
Hey all, first off thanks for this tool, it's awesome! Really a great experience, and has saved me a lot of time.

With .NET 5 coming out coming out in a few weeks, I thought it would be a good idea to upgrade and take advantage of the single executable deployment option, with assembly trimming. Ultimately the experience will be a single exe, not requiring a download of the runtime first, just like the Go discord side of things.

For it to work, we'll need to lose the `MetroModernUI` package, but I see @CarbonNeuron has a branch with WPF in the works. So I'll hold off for that to land, the create a PR following that.

Let me know what you think. Happy to help out on other stuff where I can too 🙂

**Comment by CarbonNeuron** [comment]
We can actually build a self contained assembly now as well, we did in fact look into it. But the assembly size is HUGE! Like 150-180MB even with assembly trimming turned on it only saves 5-10MB. For example, our code without this is only 3-5mb

**Comment by slang25** [comment]
Interesting, a version I have running here is 75MB and runs fine. It's not using WPF though, just an older build of master. 75MB seems about right, I think if it's under 100MB then it's better than requiring a runtime to be installed for the average user.

Perhaps there could be 2 artifacts?
