### ISSUE TITLE
Needs updating for latest beta release.

### ISSUE THREAD

**Issue by robbai** [denverquane/amonguscapture#55]
The newest beta release of Among Us is incompatible with this app, would be nice for it to work :+1:

**Comment by denverquane** [comment]
We can't really expend the effort finding memory offsets for a beta release, when the offsets will probably change again by the time the full release comes out. Not to mention, right now, we just have 1 set of offsets for all players, and most players are on the official live version of the game. Feel free to open a pull request with the beta offsets yourself though :)
