### ISSUE TITLE
[Question] What is the IPC functionality for?

### ISSUE THREAD

**Issue by TauAkiou** [denverquane/amonguscapture#59]
What exactly does it do, and what exactly is it for? I've been trying to update my fork to master, and the IPC backend isn't supported on Linux at all.

Is this safe to ignore, and can it be omitted/bypassed without any issue?

**Comment by CarbonNeuron** [comment]
> What exactly does it do, and what exactly is it for? I've been trying to update my fork to master, and the IPC backend isn't supported on Linux at all.
> 
> Is this safe to ignore, and can it be omitted/bypassed without any issue?

Inter-Process-Comunication (IPC). 
This is used when you already have the program open and click the link to link your capture in discord. When you click the link a second instance of the application is started but we need a way to get the information that the second client has to the first one (so that it can connect)

**Comment by TauAkiou** [comment]
Alright.

Is it still possible to connect manually, or has that been since written out of the server (and the capture)?

.NET Core doesn't support the method being used to create an IPC channel under Linux, so if this is the only method available, the capture is essentially broken on that platform.

**Comment by CarbonNeuron** [comment]
Connecting manually is still fully support on the client and server. (They still work the same just get their data from somewhere else). Are you sure that Linux doesn't have a concept of shared memory like pipes? I don't know if they even have url mapping. 

If not you could always "take the mutex by force". Or, if you didn't create that mutex that means there is another one of you running so you must kill it.

**Comment by CarbonNeuron** [comment]
Also the library we are using https://github.com/spazzarama/SharedMemory
Looks like it supports .net standard 2.0 for it's RPC buffer that we are using it for. Would this not work on Linux?

**Comment by TauAkiou** [comment]
URI mapping is handled by the window manager - generally Gnome or KDE. There might be another way I don't know of that's universal, but I'm still working on that.

The RPC issue seems to be more related to whether or not .NET supports the ways Linux handles RPC. Attempting to use the current code without modification (which, URI assignment notwithstanding) will throw PlatformNotSupported exceptions, so custom code is likely to be a requirement.

Getting it working may require a hacky solution involving MemoryMappedFiles

**Comment by CarbonNeuron** [comment]
I am in no way skilled with WPF at all so I have no idea if that's how you're actually supposed to do it.

**Comment by TauAkiou** [comment]
I've settled on using DBus for IPC, which is a pretty ubiquitous Linux IPC mechanism.

This does give me one more question about the current implementation:

- Does the RpcBuffer loop? As in, does it die when it finds a value or does it continue running?

**Comment by CarbonNeuron** [comment]
Yes the RPC buffer does not stop providing that service till the application closes. To allow subsequent URL handling

**Comment by TauAkiou** [comment]
I got it working - thanks for your help @CarbonNeuron . I'm closing this issue.
