### ISSUE TITLE
Will there be a version for mobile?

### ISSUE THREAD

**Issue by kmichailg** [denverquane/amonguscapture#60]
There's a lot of mobile players for this, and I have a play group that is strictly mobile. Hoping for the cross-play when the revised Among Us comes out, but I've tested this and it works perfectly on desktop! Kudos to you guys.

**Comment by CarbonNeuron** [comment]
I don't think this is really possible. We are reading game memory. Android really wont like that. Maybe if you're rooted. But also I personally have never developed for mobile.
