### ISSUE TITLE
Text same colour as background 

### ISSUE THREAD

**Issue by INGY23** [denverquane/amonguscapture#61]
Hi,

Thanks for the work on the app amazing work.

Version: 2.4.1

Just a little bug when dark mode is disabled the text for "Game status:" and "Game code:" is white so it blends in with the background.

**Comment by Kamikaze-de** [comment]
Same issue occures if dark mode is enabled. Some text is black and blends in with the background and is unreadable.

**Comment by INGY23** [comment]
@Kamikaze-de which text have you seen do that, I have only noticed the console do black on black if dark mode was disabled when the message was printed all new messages are white. Without looking I expect the text in the console is formatted when it is written.

**Comment by litetex** [comment]
There are 2 problems:
1. Some elements aren't styled at all, e.g.
![grafik](https://user-images.githubusercontent.com/40789489/97113053-1e35d400-16e8-11eb-9b2e-8f501f3a843c.png)
2. The log-text's default color does not change when toggling dark mode on or off
<details>
<summary>Broken image (click to expand)</summary>

![grafik](https://user-images.githubusercontent.com/40789489/97113042-08c0aa00-16e8-11eb-8d2e-0b80878c4705.png)
</details>

<details>
<summary>
Image for comparison</summary>

![grafik](https://user-images.githubusercontent.com/40789489/97113034-f9416100-16e7-11eb-9665-26080700a1d2.png)
</details>

**Comment by CarbonNeuron** [comment]
Well yeah. If we changed text color we would have to re print all the text to console. Also theming is not handled by me, it's handled by mahapps as we are using metro for theming

**Comment by CarbonNeuron** [comment]
It also looks like you have the code open in visual studio so if you want to try to fix it go ahead :)

**Comment by litetex** [comment]
@CarbonNeuron 
Wow, you have good eyes 😆 

I might do this in the future eventually, but it's been a while since i worked with WPF, so no guarantee.

I reviewed the code a bit and there many pieces of code that are in my opinion obsolete or need refactoring.
I will probably submit a PR for these topics first and then take a look at this issue :smile:

**Comment by CarbonNeuron** [comment]
Ah well fuck. I fixed the Game status and game code being the same color. Was an oopsies on my end lol. They are in my own fork while I am adding Cross platform support so they will be merged later.

**Comment by CarbonNeuron** [comment]
And I fixed the Console colors not matching the theme. Without rewriting all the text. :O Secrets.

**Comment by litetex** [comment]
@CarbonNeuron 
Would be nice if you reference a commit the next time, but I think it was done in this PR #73
