### ISSUE TITLE
This websocket is not associated with any guilds

### ISSUE THREAD

**Issue by realserpico** [denverquane/amonguscapture#62]
Ok so brief disclaimer I know nothing about programming. 

I ran the discord.exe bot to make sure that the bot is online, my amongus capture is working fine and it shows in the capture that the game is being hosted etc however nothing is sent back to the actual discord chat, it's only updated inside the capture.. I'm thinking that this is because of the websocket issue but I dont know how to fix this. Help please

**Comment by CarbonNeuron** [comment]
Make sure that you have your capture linked. Also join our discord for better support.
