### ISSUE TITLE
The link to the the capture program in the Bot's DM is bad

### ISSUE THREAD

**Issue by ImBytesized** [denverquane/amonguscapture#63]
The message says "Don't have the capture installed? Download it here". The link points to: https://github.com/denverquane/amonguscapture/releases/latest/download/amonguscapture**-x32.exe**

but it should be
https://github.com/denverquane/amonguscapture/releases/latest/download/amonguscapture.exe

**Comment by denverquane** [comment]
Fixed on the master branch, will release in the next few days
