### ISSUE TITLE
Stuck on "Loading"

### ISSUE THREAD

**Issue by superdeet** [denverquane/amonguscapture#64]
I closed the program while it was crashing once, and now from here on it gets stuck on "loading".  I've even tried downloading it again and that doesn't work.

**Comment by CarbonNeuron** [comment]
Tried restarting your pc? Might be some process not closing

**Comment by komlow** [comment]
I met same problem and restarting PC does not work.

**Comment by komlow** [comment]
I met the same problem and restarting PC did not work.

**Comment by denverquane** [comment]
Are you on the beta version of among us, or a cracked version? Neither of these are supported

**Comment by CarbonNeuron** [comment]
This may be an antivirus problem. being stuck on loading means that it may be waiting for the socket client to finish initializing.
