### ISSUE TITLE
Am I allowed to make this public?

### ISSUE THREAD

**Issue by RarePotato8DE** [denverquane/amonguscapture#65]
Hello,
thanks for creating such an awesome project open source!

I created an Discord Among Us Bot, which fit to my needs and in the programming language I use (C#).
So I was wondering if I would be allowed to publish "my" own version of the Among Us Bot, which is based on this project to determite in which state the game is.

Credits would obviously go to you, and this github source somewhere in the Discord Bot.

Thanks for answering.
Have a good day.

**Comment by denverquane** [comment]
Appreciate you asking :)

Yep, the code is all under an MIT License, so if you used the code in this repository, you'd just need to retain the original LICENSE file. Beyond that, MIT licenses are very lenient, so modify/distribute to your heart's content :)

If you go to the LICENSE file on Github, you can see the License terms summarized at the top: https://github.com/denverquane/amonguscapture/blob/master/LICENSE

**Comment by RarePotato8DE** [comment]
Thanks for the fast answer!
I didn't know much about the license stuff, so I wanted to ask before doing something which isn't correct.

Thanks for providing this tool for us :)

**Comment by RarePotato8DE** [comment]
Good evening,
sorry for asking, but I'm not completely sure..

So I just have to copy your LICENSE file in my repository?

Thanks in advance 👍

**Comment by denverquane** [comment]
Yes, recommend you actually read the LICENSE file in full, or do some research on the MIT license. But it contains this line:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
So if you plan on using the capture software source code within your bot, you should retain the LICENSE file of the repo in your distribution

**Comment by OperationalDev** [comment]
Yeah Among Us capture is awesome, I use it for a bot I wrote for mumble.
