### ISSUE TITLE
Is there a way to capture beta at my own risk?

### ISSUE THREAD

**Issue by Nerdtality** [denverquane/amonguscapture#66]
Is there a way to capture beta at my own risk?

**Comment by Nerdtality** [comment]
nvm I see this has already been asked, any way I can find the memory offsets my self?

**Comment by CarbonNeuron** [comment]
Cheat engine. Not for the faint of heart

**Comment by Nerdtality** [comment]
Interesting, tried a few offsets still cant find them. Any hints? There is so much data here...

**Comment by Nerdtality** [comment]
I'll continue to try. I will create a updated fork that works with the beta version. At least for offsets if I do get it.
