### ISSUE TITLE
Consider updating to game version v2020.10.22s

### ISSUE THREAD

**Issue by lippo97** [denverquane/amonguscapture#68]
Hi everyone, 
first I wanted to say thanks for this amazing software!

I'm using the currently latest version 2.4.1 and I just tried to install the latest beta version v2020.10.22s of the game.
It can't capture the game state correctly. I don't know if they will release this new version as it is right now, just consider you might need to update the memory addresses you read.

**Comment by denverquane** [comment]
https://github.com/denverquane/amonguscapture/issues/55
