### ISSUE TITLE
Not working with the public-beta version

### ISSUE THREAD

**Issue by litetex** [denverquane/amonguscapture#69]
Tested the autocapture with the current beta:

![grafik](https://user-images.githubusercontent.com/40789489/97116239-2f88db80-16fc-11eb-9bbe-9c6d96ecb376.png)

Doesn't seem to work

**Comment by denverquane** [comment]
https://github.com/denverquane/amonguscapture/issues/55

**Comment by litetex** [comment]
Wow that was fast 
Thanks for the quick feedback 😄 

Oh the same question was asked already 3 times (probably should have searched for that before asking... wooopps)
You may document that anywhere so people stop asking that :)

Off Topic question: 
How did you find the memory offsets? 
Is that anywhere documented?

**Comment by denverquane** [comment]
Yeah it's well-indicated in the Discord bot repo, and that seems to be the only way people find this repo, but it's probably worth adding to this readme, too.

And Carbon and Stenlan were largely responsible for the capture, but they both used Cheat Engine to figure out where the offsets were. That, and I think this guide was also helpful: https://github.com/shlifedev/AmongUsMemory
