### ISSUE TITLE
Client verification: FAIL.

### ISSUE THREAD

**Issue by e0d4u** [denverquane/amonguscapture#77]
i get the message [GameVerifier]: Client verification: FAIL.

**Comment by CarbonNeuron** [comment]
Are you on the cracked version, or beta, or non steam version?

**Comment by e0d4u** [comment]
setting it up for a friend, he isn’t here . it might be the cracked version

**Comment by e0d4u** [comment]
yea it’s the cracked version , does that matter ?

**Comment by CarbonNeuron** [comment]
Lol. 
We don't support the cracked version.
