### ISSUE TITLE
Do not show died players while in task state

### ISSUE THREAD

**Issue by manuco** [denverquane/amonguscapture#89]
When not in debug mode, the console shouldn't log the dead players while in Task state. It leaks information to the player using "Among us capture". The log should be displayed only once the state is changed to discuss.

When in debug mode, IMHO, the log should display as soon as the player die is detected.

**Comment by CarbonNeuron** [comment]
Yeah this was implemented in WinForms but lost when we moved to WPF. Re-added in c44de02a44afc800ea8ee86c6d1be53d84c7c88d
