### ISSUE TITLE
Smaller Release

### ISSUE THREAD

**Issue by litetex** [denverquane/amonguscapture#93]
I noticed that the AmongUs.exe in https://github.com/denverquane/amonguscapture/releases is really large (>150MB) and takes on slow internet connections very long to download.
![grafik](https://user-images.githubusercontent.com/40789489/99850060-f74eae80-2b7c-11eb-9c26-bcf13bed5dfa.png)

Possible improvements:
- [ ] Upload the release as compressed file;<br> A simple ``zip`` saves a lot of space (latest release >60%), with literally no effort to implement
![grafik](https://user-images.githubusercontent.com/40789489/99851116-e43cde00-2b7e-11eb-8065-b101836fb215.png)
- [x] Try use [Trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained); however this is experimental and can fail<br> Edit: seems like this was already done: https://github.com/denverquane/amonguscapture/commit/9e7ac6be50e31d94049a5e01c5e69b9b86168b57

**Comment by CarbonNeuron** [comment]
Trimming has saved around 50% of space so there is that. We definitely could zip the file. I think if you're on windows, they can read .zip files natively? So no user install necessary.

**Comment by CarbonNeuron** [comment]
And also, beta releases (github actions artifacts) on download are automatically zipped by github.

**Comment by litetex** [comment]
@CarbonNeuron 
>  I think if you're on windows, they can read .zip files natively?

You can right click the file and choose "Extract all..."
https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc

I think everyone should be able to do that, if not write short description into the release notes ;)

> And also, beta releases (github actions artifacts) on download are automatically zipped by github.

I think they just provide the files as ZIP but don't compress it: 
This beta release zip was built using the [same commit](https://github.com/denverquane/amonguscapture/actions/runs/358976815) as the last release and the size of the zip is identical to that of the [release exe](https://github.com/denverquane/amonguscapture/releases/tag/2.4.4) (159MB)

**Comment by CarbonNeuron** [comment]
Although it says that size is 80MB. When you download it, it is only 20

**Comment by CarbonNeuron** [comment]
Look at the latest workflow

**Comment by litetex** [comment]
Nice tiny file 👍 

Good work
