### ISSUE TITLE
Latest Among Us version broke capture

### ISSUE THREAD

**Issue by Cretezy** [denverquane/amonguscapture#97]
https://innersloth.itch.io/among-us/devlog/198476/fixes-and-a-peek-at-the-new-map

Latest version (v2020.11.17) broke capture, making this so other's don't create new tickets.

**Comment by ph0t0shop** [comment]
Bruh what did you expect

**Comment by Cretezy** [comment]
Fixed inside https://github.com/denverquane/amonguscapture/commit/8f351442422b5392c0a00b92bef5992fcfc6155e

You can use this version until a release is cut: https://github.com/denverquane/amonguscapture/suites/1550725199/artifacts/27712071 (beta version from CI)

**Comment by TheUnderTaker11** [comment]
@Cretezy That link is giving a 404.

**Comment by TheUnderTaker11** [comment]
Thank you very much @Cretezy

**Comment by CarbonNeuron** [comment]
We have released a build to our testers that we feel is stable enough to test.

**Comment by Cretezy** [comment]
@TheUnderTaker11 all the work was done by @ph0t0shop (thank you btw!), I was simply managing this issue
