### ISSUE TITLE
Self host token?

### ISSUE THREAD

**Issue by joshuacameron** [denverquane/amonguscapture#98]
I saw this in the release notes:

"This release adds the ability to add your own token into the capture for increased performance (Like running a second bot without all the hassle)."

We'd love faster performance. Where do I get this token?

![image](https://user-images.githubusercontent.com/12680312/100091486-c639eb00-2ea8-11eb-9386-fe2bf8ec4e7f.png)

**Comment by joshuacameron** [comment]
I tried my DISCORD_BOT_TOKEN_2 token from config but it was still just as slow.

**Comment by Cretezy** [comment]
This is in fact your bot token. I think the use case is when using a non-self-hosted version of AutoMuteUs.

**Comment by CarbonNeuron** [comment]
https://youtu.be/jKcEW5qpk8E
