### ISSUE TITLE
App crashes when copying text from console

### ISSUE THREAD

**Issue by joshuacameron** [denverquane/amonguscapture#99]
After I do control+c to copy highlighted text in the console it crashes, running latest version.

![image](https://user-images.githubusercontent.com/12680312/100091516-cc2fcc00-2ea8-11eb-8b45-e44bf2c3f387.png)

**Comment by joshuacameron** [comment]
Reproduces bug 100% of time

**Comment by CarbonNeuron** [comment]
Yeah. Probably going to need to switch to framework dependant releases to fix it.

**Comment by CarbonNeuron** [comment]
Yep. This is caused by trimming. It is removing the COM access to the clipboard and causing it to crash.

**Comment by eXpl0it3r** [comment]
Also crashes when you click on the "Game code" field. You get the info box that it was copied and then a few seconds later the application crashes.

**Comment by CarbonNeuron** [comment]
Fixed in latest release, commit ac27521fbdc6514bbf8fe05413737eca764ddcfe

**Comment by eXpl0it3r** [comment]
It doesn't seem to crash anymore, but clicking on the code now doesn't initiate copying, is that correct behavior?

**Comment by CarbonNeuron** [comment]
Yep. Sadly the fix was to remove copying from the app altogether.
